<?php
/**
 * CheckState
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Vouchsafe
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vouchsafe API docs
 *
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vouchsafe\Model;
use \Vouchsafe\ObjectSerializer;

/**
 * CheckState Class Doc Comment
 *
 * @category Class
 * @package  Vouchsafe
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CheckState
{
    /**
     * Possible values of this enum
     */
    public const PASS = 'PASS';

    public const FAIL = 'FAIL';

    public const PARTIAL = 'PARTIAL';

    public const NOT_PERFORMED = 'NOT_PERFORMED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PASS,
            self::FAIL,
            self::PARTIAL,
            self::NOT_PERFORMED
        ];
    }
}


