<?php
/**
 * ApiBankAccountCheckResultRecordedPreviousSubmissionsInner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Vouchsafe\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vouchsafe API docs
 *
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vouchsafe\OpenAPI\Model;

use \ArrayAccess;
use \Vouchsafe\OpenAPI\ObjectSerializer;

/**
 * ApiBankAccountCheckResultRecordedPreviousSubmissionsInner Class Doc Comment
 *
 * @category Class
 * @package  Vouchsafe\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ApiBankAccountCheckResultRecordedPreviousSubmissionsInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Api_BankAccountCheck__result_recorded_previous_submissions_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'extracted_details' => '\Vouchsafe\OpenAPI\Model\ApiBankAccountCheckResultRecordedPreviousSubmissionsInnerExtractedDetails',
        'artefacts' => '\Vouchsafe\OpenAPI\Model\ApiVideoSelfieCheckResultRecordedPreviousSubmissionsInnerArtefactsInner[]',
        'evidence_type' => 'string',
        'evidence_route' => 'string',
        'validations' => '\Vouchsafe\OpenAPI\Model\ApiBankAccountCheckResultRecordedPreviousSubmissionsInnerValidations',
        'created_at' => 'string',
        'status' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'extracted_details' => null,
        'artefacts' => null,
        'evidence_type' => null,
        'evidence_route' => null,
        'validations' => null,
        'created_at' => null,
        'status' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'extracted_details' => false,
        'artefacts' => false,
        'evidence_type' => false,
        'evidence_route' => false,
        'validations' => false,
        'created_at' => false,
        'status' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'extracted_details' => 'extracted_details',
        'artefacts' => 'artefacts',
        'evidence_type' => 'evidence_type',
        'evidence_route' => 'evidence_route',
        'validations' => 'validations',
        'created_at' => 'created_at',
        'status' => 'status'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'extracted_details' => 'setExtractedDetails',
        'artefacts' => 'setArtefacts',
        'evidence_type' => 'setEvidenceType',
        'evidence_route' => 'setEvidenceRoute',
        'validations' => 'setValidations',
        'created_at' => 'setCreatedAt',
        'status' => 'setStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'extracted_details' => 'getExtractedDetails',
        'artefacts' => 'getArtefacts',
        'evidence_type' => 'getEvidenceType',
        'evidence_route' => 'getEvidenceRoute',
        'validations' => 'getValidations',
        'created_at' => 'getCreatedAt',
        'status' => 'getStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const EVIDENCE_TYPE_MANUAL_ENTRY = 'ManualEntry';
    public const EVIDENCE_TYPE_CLAIMS_TO_VERIFY = 'ClaimsToVerify';
    public const EVIDENCE_TYPE_EVISA = 'evisa';
    public const EVIDENCE_TYPE_SCOT_ACCOUNT = 'ScotAccount';
    public const EVIDENCE_TYPE_UNFAMILIAR_PHOTO_ID = 'unfamiliar_photo_id';
    public const EVIDENCE_TYPE_PASSPORT = 'passport';
    public const EVIDENCE_TYPE_DRIVING_LICENCE = 'driving_licence';
    public const EVIDENCE_TYPE_YOUNG_SCOT = 'young_scot';
    public const EVIDENCE_TYPE_NATIONAL_ENTITLEMENT_CARD = 'national_entitlement_card';
    public const EVIDENCE_TYPE_NATIONAL_ID = 'national_id';
    public const EVIDENCE_TYPE_CITIZEN_CARD = 'citizen_card';
    public const EVIDENCE_TYPE_BIRTH_OR_ADOPTION_CERTIFICATE = 'birth_or_adoption_certificate';
    public const EVIDENCE_TYPE_MARRIAGE_CERTIFICATE = 'marriage_certificate';
    public const EVIDENCE_TYPE_NATURALISATION_OR_REG_CERTIFICATE = 'naturalisation_or_reg_certificate';
    public const EVIDENCE_TYPE_EDUCATION_CERTIFICATE = 'education_certificate';
    public const EVIDENCE_TYPE_PAYE_TAX_SUMMARY = 'paye_tax_summary';
    public const EVIDENCE_TYPE_PAYSLIP = 'payslip';
    public const EVIDENCE_TYPE_PENSION_ANNUAL_STATEMENT = 'pension_annual_statement';
    public const EVIDENCE_TYPE_BENEFITS_LETTER = 'benefits_letter';
    public const EVIDENCE_TYPE_NHS_LETTER = 'nhs_letter';
    public const EVIDENCE_TYPE_BANK_STATEMENT = 'bank_statement';
    public const EVIDENCE_TYPE_CREDIT_CARD_STATEMENT = 'credit_card_statement';
    public const EVIDENCE_TYPE_MORTGAGE_STATEMENT = 'mortgage_statement';
    public const EVIDENCE_TYPE_INSURANCE_POLICY_AGREEMENT = 'insurance_policy_agreement';
    public const EVIDENCE_TYPE_UTILITY_BILL = 'utility_bill';
    public const EVIDENCE_TYPE_MOBILE_PHONE_BILL = 'mobile_phone_bill';
    public const EVIDENCE_TYPE_HMPPS_LETTER = 'hmpps_letter';
    public const EVIDENCE_TYPE_OLDER_PERSON_BUS_PASS = 'older_person_bus_pass';
    public const EVIDENCE_TYPE_OPEN_BANKING = 'open_banking';
    public const EVIDENCE_ROUTE_PHOTO_ID = 'photo_id';
    public const EVIDENCE_ROUTE_SUPPORTING_DOCUMENT = 'supporting_document';
    public const EVIDENCE_ROUTE_BANK_ACCOUNT = 'bank_account';
    public const EVIDENCE_ROUTE_EVISA = 'evisa';
    public const EVIDENCE_ROUTE_VOUCH = 'vouch';
    public const STATUS_PASS = 'pass';
    public const STATUS_FAIL = 'fail';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEvidenceTypeAllowableValues()
    {
        return [
            self::EVIDENCE_TYPE_MANUAL_ENTRY,
            self::EVIDENCE_TYPE_CLAIMS_TO_VERIFY,
            self::EVIDENCE_TYPE_EVISA,
            self::EVIDENCE_TYPE_SCOT_ACCOUNT,
            self::EVIDENCE_TYPE_UNFAMILIAR_PHOTO_ID,
            self::EVIDENCE_TYPE_PASSPORT,
            self::EVIDENCE_TYPE_DRIVING_LICENCE,
            self::EVIDENCE_TYPE_YOUNG_SCOT,
            self::EVIDENCE_TYPE_NATIONAL_ENTITLEMENT_CARD,
            self::EVIDENCE_TYPE_NATIONAL_ID,
            self::EVIDENCE_TYPE_CITIZEN_CARD,
            self::EVIDENCE_TYPE_BIRTH_OR_ADOPTION_CERTIFICATE,
            self::EVIDENCE_TYPE_MARRIAGE_CERTIFICATE,
            self::EVIDENCE_TYPE_NATURALISATION_OR_REG_CERTIFICATE,
            self::EVIDENCE_TYPE_EDUCATION_CERTIFICATE,
            self::EVIDENCE_TYPE_PAYE_TAX_SUMMARY,
            self::EVIDENCE_TYPE_PAYSLIP,
            self::EVIDENCE_TYPE_PENSION_ANNUAL_STATEMENT,
            self::EVIDENCE_TYPE_BENEFITS_LETTER,
            self::EVIDENCE_TYPE_NHS_LETTER,
            self::EVIDENCE_TYPE_BANK_STATEMENT,
            self::EVIDENCE_TYPE_CREDIT_CARD_STATEMENT,
            self::EVIDENCE_TYPE_MORTGAGE_STATEMENT,
            self::EVIDENCE_TYPE_INSURANCE_POLICY_AGREEMENT,
            self::EVIDENCE_TYPE_UTILITY_BILL,
            self::EVIDENCE_TYPE_MOBILE_PHONE_BILL,
            self::EVIDENCE_TYPE_HMPPS_LETTER,
            self::EVIDENCE_TYPE_OLDER_PERSON_BUS_PASS,
            self::EVIDENCE_TYPE_OPEN_BANKING,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEvidenceRouteAllowableValues()
    {
        return [
            self::EVIDENCE_ROUTE_PHOTO_ID,
            self::EVIDENCE_ROUTE_SUPPORTING_DOCUMENT,
            self::EVIDENCE_ROUTE_BANK_ACCOUNT,
            self::EVIDENCE_ROUTE_EVISA,
            self::EVIDENCE_ROUTE_VOUCH,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_PASS,
            self::STATUS_FAIL,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('extracted_details', $data ?? [], null);
        $this->setIfExists('artefacts', $data ?? [], null);
        $this->setIfExists('evidence_type', $data ?? [], null);
        $this->setIfExists('evidence_route', $data ?? [], null);
        $this->setIfExists('validations', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['extracted_details'] === null) {
            $invalidProperties[] = "'extracted_details' can't be null";
        }
        if ($this->container['evidence_type'] === null) {
            $invalidProperties[] = "'evidence_type' can't be null";
        }
        $allowedValues = $this->getEvidenceTypeAllowableValues();
        if (!is_null($this->container['evidence_type']) && !in_array($this->container['evidence_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'evidence_type', must be one of '%s'",
                $this->container['evidence_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['evidence_route'] === null) {
            $invalidProperties[] = "'evidence_route' can't be null";
        }
        $allowedValues = $this->getEvidenceRouteAllowableValues();
        if (!is_null($this->container['evidence_route']) && !in_array($this->container['evidence_route'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'evidence_route', must be one of '%s'",
                $this->container['evidence_route'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['validations'] === null) {
            $invalidProperties[] = "'validations' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets extracted_details
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiBankAccountCheckResultRecordedPreviousSubmissionsInnerExtractedDetails
     */
    public function getExtractedDetails()
    {
        return $this->container['extracted_details'];
    }

    /**
     * Sets extracted_details
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiBankAccountCheckResultRecordedPreviousSubmissionsInnerExtractedDetails $extracted_details extracted_details
     *
     * @return self
     */
    public function setExtractedDetails($extracted_details)
    {
        if (is_null($extracted_details)) {
            throw new \InvalidArgumentException('non-nullable extracted_details cannot be null');
        }
        $this->container['extracted_details'] = $extracted_details;

        return $this;
    }

    /**
     * Gets artefacts
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiVideoSelfieCheckResultRecordedPreviousSubmissionsInnerArtefactsInner[]|null
     */
    public function getArtefacts()
    {
        return $this->container['artefacts'];
    }

    /**
     * Sets artefacts
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiVideoSelfieCheckResultRecordedPreviousSubmissionsInnerArtefactsInner[]|null $artefacts artefacts
     *
     * @return self
     */
    public function setArtefacts($artefacts)
    {
        if (is_null($artefacts)) {
            throw new \InvalidArgumentException('non-nullable artefacts cannot be null');
        }
        $this->container['artefacts'] = $artefacts;

        return $this;
    }

    /**
     * Gets evidence_type
     *
     * @return string
     */
    public function getEvidenceType()
    {
        return $this->container['evidence_type'];
    }

    /**
     * Sets evidence_type
     *
     * @param string $evidence_type evidence_type
     *
     * @return self
     */
    public function setEvidenceType($evidence_type)
    {
        if (is_null($evidence_type)) {
            throw new \InvalidArgumentException('non-nullable evidence_type cannot be null');
        }
        $allowedValues = $this->getEvidenceTypeAllowableValues();
        if (!in_array($evidence_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'evidence_type', must be one of '%s'",
                    $evidence_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['evidence_type'] = $evidence_type;

        return $this;
    }

    /**
     * Gets evidence_route
     *
     * @return string
     */
    public function getEvidenceRoute()
    {
        return $this->container['evidence_route'];
    }

    /**
     * Sets evidence_route
     *
     * @param string $evidence_route evidence_route
     *
     * @return self
     */
    public function setEvidenceRoute($evidence_route)
    {
        if (is_null($evidence_route)) {
            throw new \InvalidArgumentException('non-nullable evidence_route cannot be null');
        }
        $allowedValues = $this->getEvidenceRouteAllowableValues();
        if (!in_array($evidence_route, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'evidence_route', must be one of '%s'",
                    $evidence_route,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['evidence_route'] = $evidence_route;

        return $this;
    }

    /**
     * Gets validations
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiBankAccountCheckResultRecordedPreviousSubmissionsInnerValidations
     */
    public function getValidations()
    {
        return $this->container['validations'];
    }

    /**
     * Sets validations
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiBankAccountCheckResultRecordedPreviousSubmissionsInnerValidations $validations validations
     *
     * @return self
     */
    public function setValidations($validations)
    {
        if (is_null($validations)) {
            throw new \InvalidArgumentException('non-nullable validations cannot be null');
        }
        $this->container['validations'] = $validations;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


