<?php
/**
 * ApiPhotoIdEvidenceItemValidations
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Vouchsafe\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vouchsafe API docs
 *
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vouchsafe\OpenAPI\Model;

use \ArrayAccess;
use \Vouchsafe\OpenAPI\ObjectSerializer;

/**
 * ApiPhotoIdEvidenceItemValidations Class Doc Comment
 *
 * @category Class
 * @package  Vouchsafe\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ApiPhotoIdEvidenceItemValidations implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Api_PhotoIdEvidenceItem__validations';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'referee_biometrics_dissimilar' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth',
        'referee_over18' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth',
        'issuing_country_allowed' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth',
        'icao_format_valid' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth',
        'names_consistent' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth',
        'dates_of_birth_consistent' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth',
        'has_not_expired' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth',
        'face_match' => '\Vouchsafe\OpenAPI\Model\ApiVideoSelfieCheckValidationsRefereeDissimilarityCheck',
        'not_sample_or_internal_use' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth',
        'identifier_format_valid' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth',
        'matches_issuer_database' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth',
        'compound_identifiers_match' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth',
        'security_features_present' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth',
        'document_borders_detected' => '\Vouchsafe\OpenAPI\Model\ApiVideoSelfieCheckValidationsRefereeDissimilarityCheck',
        'required_fields_extracted' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'referee_biometrics_dissimilar' => null,
        'referee_over18' => null,
        'issuing_country_allowed' => null,
        'icao_format_valid' => null,
        'names_consistent' => null,
        'dates_of_birth_consistent' => null,
        'has_not_expired' => null,
        'face_match' => null,
        'not_sample_or_internal_use' => null,
        'identifier_format_valid' => null,
        'matches_issuer_database' => null,
        'compound_identifiers_match' => null,
        'security_features_present' => null,
        'document_borders_detected' => null,
        'required_fields_extracted' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'referee_biometrics_dissimilar' => false,
        'referee_over18' => false,
        'issuing_country_allowed' => false,
        'icao_format_valid' => false,
        'names_consistent' => false,
        'dates_of_birth_consistent' => false,
        'has_not_expired' => false,
        'face_match' => false,
        'not_sample_or_internal_use' => false,
        'identifier_format_valid' => false,
        'matches_issuer_database' => false,
        'compound_identifiers_match' => false,
        'security_features_present' => false,
        'document_borders_detected' => false,
        'required_fields_extracted' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'referee_biometrics_dissimilar' => 'referee_biometrics_dissimilar',
        'referee_over18' => 'referee_over18',
        'issuing_country_allowed' => 'issuing_country_allowed',
        'icao_format_valid' => 'icao_format_valid',
        'names_consistent' => 'names_consistent',
        'dates_of_birth_consistent' => 'dates_of_birth_consistent',
        'has_not_expired' => 'has_not_expired',
        'face_match' => 'face_match',
        'not_sample_or_internal_use' => 'not_sample_or_internal_use',
        'identifier_format_valid' => 'identifier_format_valid',
        'matches_issuer_database' => 'matches_issuer_database',
        'compound_identifiers_match' => 'compound_identifiers_match',
        'security_features_present' => 'security_features_present',
        'document_borders_detected' => 'document_borders_detected',
        'required_fields_extracted' => 'required_fields_extracted'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'referee_biometrics_dissimilar' => 'setRefereeBiometricsDissimilar',
        'referee_over18' => 'setRefereeOver18',
        'issuing_country_allowed' => 'setIssuingCountryAllowed',
        'icao_format_valid' => 'setIcaoFormatValid',
        'names_consistent' => 'setNamesConsistent',
        'dates_of_birth_consistent' => 'setDatesOfBirthConsistent',
        'has_not_expired' => 'setHasNotExpired',
        'face_match' => 'setFaceMatch',
        'not_sample_or_internal_use' => 'setNotSampleOrInternalUse',
        'identifier_format_valid' => 'setIdentifierFormatValid',
        'matches_issuer_database' => 'setMatchesIssuerDatabase',
        'compound_identifiers_match' => 'setCompoundIdentifiersMatch',
        'security_features_present' => 'setSecurityFeaturesPresent',
        'document_borders_detected' => 'setDocumentBordersDetected',
        'required_fields_extracted' => 'setRequiredFieldsExtracted'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'referee_biometrics_dissimilar' => 'getRefereeBiometricsDissimilar',
        'referee_over18' => 'getRefereeOver18',
        'issuing_country_allowed' => 'getIssuingCountryAllowed',
        'icao_format_valid' => 'getIcaoFormatValid',
        'names_consistent' => 'getNamesConsistent',
        'dates_of_birth_consistent' => 'getDatesOfBirthConsistent',
        'has_not_expired' => 'getHasNotExpired',
        'face_match' => 'getFaceMatch',
        'not_sample_or_internal_use' => 'getNotSampleOrInternalUse',
        'identifier_format_valid' => 'getIdentifierFormatValid',
        'matches_issuer_database' => 'getMatchesIssuerDatabase',
        'compound_identifiers_match' => 'getCompoundIdentifiersMatch',
        'security_features_present' => 'getSecurityFeaturesPresent',
        'document_borders_detected' => 'getDocumentBordersDetected',
        'required_fields_extracted' => 'getRequiredFieldsExtracted'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('referee_biometrics_dissimilar', $data ?? [], null);
        $this->setIfExists('referee_over18', $data ?? [], null);
        $this->setIfExists('issuing_country_allowed', $data ?? [], null);
        $this->setIfExists('icao_format_valid', $data ?? [], null);
        $this->setIfExists('names_consistent', $data ?? [], null);
        $this->setIfExists('dates_of_birth_consistent', $data ?? [], null);
        $this->setIfExists('has_not_expired', $data ?? [], null);
        $this->setIfExists('face_match', $data ?? [], null);
        $this->setIfExists('not_sample_or_internal_use', $data ?? [], null);
        $this->setIfExists('identifier_format_valid', $data ?? [], null);
        $this->setIfExists('matches_issuer_database', $data ?? [], null);
        $this->setIfExists('compound_identifiers_match', $data ?? [], null);
        $this->setIfExists('security_features_present', $data ?? [], null);
        $this->setIfExists('document_borders_detected', $data ?? [], null);
        $this->setIfExists('required_fields_extracted', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['document_borders_detected'] === null) {
            $invalidProperties[] = "'document_borders_detected' can't be null";
        }
        if ($this->container['required_fields_extracted'] === null) {
            $invalidProperties[] = "'required_fields_extracted' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets referee_biometrics_dissimilar
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null
     */
    public function getRefereeBiometricsDissimilar()
    {
        return $this->container['referee_biometrics_dissimilar'];
    }

    /**
     * Sets referee_biometrics_dissimilar
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null $referee_biometrics_dissimilar referee_biometrics_dissimilar
     *
     * @return self
     */
    public function setRefereeBiometricsDissimilar($referee_biometrics_dissimilar)
    {
        if (is_null($referee_biometrics_dissimilar)) {
            throw new \InvalidArgumentException('non-nullable referee_biometrics_dissimilar cannot be null');
        }
        $this->container['referee_biometrics_dissimilar'] = $referee_biometrics_dissimilar;

        return $this;
    }

    /**
     * Gets referee_over18
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null
     */
    public function getRefereeOver18()
    {
        return $this->container['referee_over18'];
    }

    /**
     * Sets referee_over18
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null $referee_over18 referee_over18
     *
     * @return self
     */
    public function setRefereeOver18($referee_over18)
    {
        if (is_null($referee_over18)) {
            throw new \InvalidArgumentException('non-nullable referee_over18 cannot be null');
        }
        $this->container['referee_over18'] = $referee_over18;

        return $this;
    }

    /**
     * Gets issuing_country_allowed
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null
     */
    public function getIssuingCountryAllowed()
    {
        return $this->container['issuing_country_allowed'];
    }

    /**
     * Sets issuing_country_allowed
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null $issuing_country_allowed issuing_country_allowed
     *
     * @return self
     */
    public function setIssuingCountryAllowed($issuing_country_allowed)
    {
        if (is_null($issuing_country_allowed)) {
            throw new \InvalidArgumentException('non-nullable issuing_country_allowed cannot be null');
        }
        $this->container['issuing_country_allowed'] = $issuing_country_allowed;

        return $this;
    }

    /**
     * Gets icao_format_valid
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null
     */
    public function getIcaoFormatValid()
    {
        return $this->container['icao_format_valid'];
    }

    /**
     * Sets icao_format_valid
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null $icao_format_valid icao_format_valid
     *
     * @return self
     */
    public function setIcaoFormatValid($icao_format_valid)
    {
        if (is_null($icao_format_valid)) {
            throw new \InvalidArgumentException('non-nullable icao_format_valid cannot be null');
        }
        $this->container['icao_format_valid'] = $icao_format_valid;

        return $this;
    }

    /**
     * Gets names_consistent
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null
     */
    public function getNamesConsistent()
    {
        return $this->container['names_consistent'];
    }

    /**
     * Sets names_consistent
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null $names_consistent names_consistent
     *
     * @return self
     */
    public function setNamesConsistent($names_consistent)
    {
        if (is_null($names_consistent)) {
            throw new \InvalidArgumentException('non-nullable names_consistent cannot be null');
        }
        $this->container['names_consistent'] = $names_consistent;

        return $this;
    }

    /**
     * Gets dates_of_birth_consistent
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null
     */
    public function getDatesOfBirthConsistent()
    {
        return $this->container['dates_of_birth_consistent'];
    }

    /**
     * Sets dates_of_birth_consistent
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null $dates_of_birth_consistent dates_of_birth_consistent
     *
     * @return self
     */
    public function setDatesOfBirthConsistent($dates_of_birth_consistent)
    {
        if (is_null($dates_of_birth_consistent)) {
            throw new \InvalidArgumentException('non-nullable dates_of_birth_consistent cannot be null');
        }
        $this->container['dates_of_birth_consistent'] = $dates_of_birth_consistent;

        return $this;
    }

    /**
     * Gets has_not_expired
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null
     */
    public function getHasNotExpired()
    {
        return $this->container['has_not_expired'];
    }

    /**
     * Sets has_not_expired
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null $has_not_expired has_not_expired
     *
     * @return self
     */
    public function setHasNotExpired($has_not_expired)
    {
        if (is_null($has_not_expired)) {
            throw new \InvalidArgumentException('non-nullable has_not_expired cannot be null');
        }
        $this->container['has_not_expired'] = $has_not_expired;

        return $this;
    }

    /**
     * Gets face_match
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiVideoSelfieCheckValidationsRefereeDissimilarityCheck|null
     */
    public function getFaceMatch()
    {
        return $this->container['face_match'];
    }

    /**
     * Sets face_match
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiVideoSelfieCheckValidationsRefereeDissimilarityCheck|null $face_match face_match
     *
     * @return self
     */
    public function setFaceMatch($face_match)
    {
        if (is_null($face_match)) {
            throw new \InvalidArgumentException('non-nullable face_match cannot be null');
        }
        $this->container['face_match'] = $face_match;

        return $this;
    }

    /**
     * Gets not_sample_or_internal_use
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null
     */
    public function getNotSampleOrInternalUse()
    {
        return $this->container['not_sample_or_internal_use'];
    }

    /**
     * Sets not_sample_or_internal_use
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null $not_sample_or_internal_use not_sample_or_internal_use
     *
     * @return self
     */
    public function setNotSampleOrInternalUse($not_sample_or_internal_use)
    {
        if (is_null($not_sample_or_internal_use)) {
            throw new \InvalidArgumentException('non-nullable not_sample_or_internal_use cannot be null');
        }
        $this->container['not_sample_or_internal_use'] = $not_sample_or_internal_use;

        return $this;
    }

    /**
     * Gets identifier_format_valid
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null
     */
    public function getIdentifierFormatValid()
    {
        return $this->container['identifier_format_valid'];
    }

    /**
     * Sets identifier_format_valid
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null $identifier_format_valid identifier_format_valid
     *
     * @return self
     */
    public function setIdentifierFormatValid($identifier_format_valid)
    {
        if (is_null($identifier_format_valid)) {
            throw new \InvalidArgumentException('non-nullable identifier_format_valid cannot be null');
        }
        $this->container['identifier_format_valid'] = $identifier_format_valid;

        return $this;
    }

    /**
     * Gets matches_issuer_database
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null
     */
    public function getMatchesIssuerDatabase()
    {
        return $this->container['matches_issuer_database'];
    }

    /**
     * Sets matches_issuer_database
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null $matches_issuer_database matches_issuer_database
     *
     * @return self
     */
    public function setMatchesIssuerDatabase($matches_issuer_database)
    {
        if (is_null($matches_issuer_database)) {
            throw new \InvalidArgumentException('non-nullable matches_issuer_database cannot be null');
        }
        $this->container['matches_issuer_database'] = $matches_issuer_database;

        return $this;
    }

    /**
     * Gets compound_identifiers_match
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null
     */
    public function getCompoundIdentifiersMatch()
    {
        return $this->container['compound_identifiers_match'];
    }

    /**
     * Sets compound_identifiers_match
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null $compound_identifiers_match compound_identifiers_match
     *
     * @return self
     */
    public function setCompoundIdentifiersMatch($compound_identifiers_match)
    {
        if (is_null($compound_identifiers_match)) {
            throw new \InvalidArgumentException('non-nullable compound_identifiers_match cannot be null');
        }
        $this->container['compound_identifiers_match'] = $compound_identifiers_match;

        return $this;
    }

    /**
     * Gets security_features_present
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null
     */
    public function getSecurityFeaturesPresent()
    {
        return $this->container['security_features_present'];
    }

    /**
     * Sets security_features_present
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null $security_features_present security_features_present
     *
     * @return self
     */
    public function setSecurityFeaturesPresent($security_features_present)
    {
        if (is_null($security_features_present)) {
            throw new \InvalidArgumentException('non-nullable security_features_present cannot be null');
        }
        $this->container['security_features_present'] = $security_features_present;

        return $this;
    }

    /**
     * Gets document_borders_detected
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiVideoSelfieCheckValidationsRefereeDissimilarityCheck
     */
    public function getDocumentBordersDetected()
    {
        return $this->container['document_borders_detected'];
    }

    /**
     * Sets document_borders_detected
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiVideoSelfieCheckValidationsRefereeDissimilarityCheck $document_borders_detected document_borders_detected
     *
     * @return self
     */
    public function setDocumentBordersDetected($document_borders_detected)
    {
        if (is_null($document_borders_detected)) {
            throw new \InvalidArgumentException('non-nullable document_borders_detected cannot be null');
        }
        $this->container['document_borders_detected'] = $document_borders_detected;

        return $this;
    }

    /**
     * Gets required_fields_extracted
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth
     */
    public function getRequiredFieldsExtracted()
    {
        return $this->container['required_fields_extracted'];
    }

    /**
     * Sets required_fields_extracted
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth $required_fields_extracted required_fields_extracted
     *
     * @return self
     */
    public function setRequiredFieldsExtracted($required_fields_extracted)
    {
        if (is_null($required_fields_extracted)) {
            throw new \InvalidArgumentException('non-nullable required_fields_extracted cannot be null');
        }
        $this->container['required_fields_extracted'] = $required_fields_extracted;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


