<?php
/**
 * ApiSupportingDocEvidenceItemValidations
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Vouchsafe\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vouchsafe API docs
 *
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vouchsafe\OpenAPI\Model;

use \ArrayAccess;
use \Vouchsafe\OpenAPI\ObjectSerializer;

/**
 * ApiSupportingDocEvidenceItemValidations Class Doc Comment
 *
 * @category Class
 * @package  Vouchsafe\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ApiSupportingDocEvidenceItemValidations implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Api_SupportingDocEvidenceItem__validations';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'referee_biometrics_dissimilar' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth',
        'addresses_consistent' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth',
        'dates_of_birth_consistent' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth',
        'names_consistent' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth',
        'date_fields_valid' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth',
        'tampering_signals_check' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth',
        'document_complete_and_legible' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth',
        'document_age_valid' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth',
        'document_unique' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth',
        'category_match' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth',
        'required_fields_extracted' => '\Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'referee_biometrics_dissimilar' => null,
        'addresses_consistent' => null,
        'dates_of_birth_consistent' => null,
        'names_consistent' => null,
        'date_fields_valid' => null,
        'tampering_signals_check' => null,
        'document_complete_and_legible' => null,
        'document_age_valid' => null,
        'document_unique' => null,
        'category_match' => null,
        'required_fields_extracted' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'referee_biometrics_dissimilar' => false,
        'addresses_consistent' => false,
        'dates_of_birth_consistent' => false,
        'names_consistent' => false,
        'date_fields_valid' => false,
        'tampering_signals_check' => false,
        'document_complete_and_legible' => false,
        'document_age_valid' => false,
        'document_unique' => false,
        'category_match' => false,
        'required_fields_extracted' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'referee_biometrics_dissimilar' => 'referee_biometrics_dissimilar',
        'addresses_consistent' => 'addresses_consistent',
        'dates_of_birth_consistent' => 'dates_of_birth_consistent',
        'names_consistent' => 'names_consistent',
        'date_fields_valid' => 'date_fields_valid',
        'tampering_signals_check' => 'tampering_signals_check',
        'document_complete_and_legible' => 'document_complete_and_legible',
        'document_age_valid' => 'document_age_valid',
        'document_unique' => 'document_unique',
        'category_match' => 'category_match',
        'required_fields_extracted' => 'required_fields_extracted'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'referee_biometrics_dissimilar' => 'setRefereeBiometricsDissimilar',
        'addresses_consistent' => 'setAddressesConsistent',
        'dates_of_birth_consistent' => 'setDatesOfBirthConsistent',
        'names_consistent' => 'setNamesConsistent',
        'date_fields_valid' => 'setDateFieldsValid',
        'tampering_signals_check' => 'setTamperingSignalsCheck',
        'document_complete_and_legible' => 'setDocumentCompleteAndLegible',
        'document_age_valid' => 'setDocumentAgeValid',
        'document_unique' => 'setDocumentUnique',
        'category_match' => 'setCategoryMatch',
        'required_fields_extracted' => 'setRequiredFieldsExtracted'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'referee_biometrics_dissimilar' => 'getRefereeBiometricsDissimilar',
        'addresses_consistent' => 'getAddressesConsistent',
        'dates_of_birth_consistent' => 'getDatesOfBirthConsistent',
        'names_consistent' => 'getNamesConsistent',
        'date_fields_valid' => 'getDateFieldsValid',
        'tampering_signals_check' => 'getTamperingSignalsCheck',
        'document_complete_and_legible' => 'getDocumentCompleteAndLegible',
        'document_age_valid' => 'getDocumentAgeValid',
        'document_unique' => 'getDocumentUnique',
        'category_match' => 'getCategoryMatch',
        'required_fields_extracted' => 'getRequiredFieldsExtracted'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('referee_biometrics_dissimilar', $data ?? [], null);
        $this->setIfExists('addresses_consistent', $data ?? [], null);
        $this->setIfExists('dates_of_birth_consistent', $data ?? [], null);
        $this->setIfExists('names_consistent', $data ?? [], null);
        $this->setIfExists('date_fields_valid', $data ?? [], null);
        $this->setIfExists('tampering_signals_check', $data ?? [], null);
        $this->setIfExists('document_complete_and_legible', $data ?? [], null);
        $this->setIfExists('document_age_valid', $data ?? [], null);
        $this->setIfExists('document_unique', $data ?? [], null);
        $this->setIfExists('category_match', $data ?? [], null);
        $this->setIfExists('required_fields_extracted', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['required_fields_extracted'] === null) {
            $invalidProperties[] = "'required_fields_extracted' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets referee_biometrics_dissimilar
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null
     */
    public function getRefereeBiometricsDissimilar()
    {
        return $this->container['referee_biometrics_dissimilar'];
    }

    /**
     * Sets referee_biometrics_dissimilar
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null $referee_biometrics_dissimilar referee_biometrics_dissimilar
     *
     * @return self
     */
    public function setRefereeBiometricsDissimilar($referee_biometrics_dissimilar)
    {
        if (is_null($referee_biometrics_dissimilar)) {
            throw new \InvalidArgumentException('non-nullable referee_biometrics_dissimilar cannot be null');
        }
        $this->container['referee_biometrics_dissimilar'] = $referee_biometrics_dissimilar;

        return $this;
    }

    /**
     * Gets addresses_consistent
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null
     */
    public function getAddressesConsistent()
    {
        return $this->container['addresses_consistent'];
    }

    /**
     * Sets addresses_consistent
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null $addresses_consistent addresses_consistent
     *
     * @return self
     */
    public function setAddressesConsistent($addresses_consistent)
    {
        if (is_null($addresses_consistent)) {
            throw new \InvalidArgumentException('non-nullable addresses_consistent cannot be null');
        }
        $this->container['addresses_consistent'] = $addresses_consistent;

        return $this;
    }

    /**
     * Gets dates_of_birth_consistent
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null
     */
    public function getDatesOfBirthConsistent()
    {
        return $this->container['dates_of_birth_consistent'];
    }

    /**
     * Sets dates_of_birth_consistent
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null $dates_of_birth_consistent dates_of_birth_consistent
     *
     * @return self
     */
    public function setDatesOfBirthConsistent($dates_of_birth_consistent)
    {
        if (is_null($dates_of_birth_consistent)) {
            throw new \InvalidArgumentException('non-nullable dates_of_birth_consistent cannot be null');
        }
        $this->container['dates_of_birth_consistent'] = $dates_of_birth_consistent;

        return $this;
    }

    /**
     * Gets names_consistent
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null
     */
    public function getNamesConsistent()
    {
        return $this->container['names_consistent'];
    }

    /**
     * Sets names_consistent
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null $names_consistent names_consistent
     *
     * @return self
     */
    public function setNamesConsistent($names_consistent)
    {
        if (is_null($names_consistent)) {
            throw new \InvalidArgumentException('non-nullable names_consistent cannot be null');
        }
        $this->container['names_consistent'] = $names_consistent;

        return $this;
    }

    /**
     * Gets date_fields_valid
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null
     */
    public function getDateFieldsValid()
    {
        return $this->container['date_fields_valid'];
    }

    /**
     * Sets date_fields_valid
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null $date_fields_valid date_fields_valid
     *
     * @return self
     */
    public function setDateFieldsValid($date_fields_valid)
    {
        if (is_null($date_fields_valid)) {
            throw new \InvalidArgumentException('non-nullable date_fields_valid cannot be null');
        }
        $this->container['date_fields_valid'] = $date_fields_valid;

        return $this;
    }

    /**
     * Gets tampering_signals_check
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null
     */
    public function getTamperingSignalsCheck()
    {
        return $this->container['tampering_signals_check'];
    }

    /**
     * Sets tampering_signals_check
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null $tampering_signals_check tampering_signals_check
     *
     * @return self
     */
    public function setTamperingSignalsCheck($tampering_signals_check)
    {
        if (is_null($tampering_signals_check)) {
            throw new \InvalidArgumentException('non-nullable tampering_signals_check cannot be null');
        }
        $this->container['tampering_signals_check'] = $tampering_signals_check;

        return $this;
    }

    /**
     * Gets document_complete_and_legible
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null
     */
    public function getDocumentCompleteAndLegible()
    {
        return $this->container['document_complete_and_legible'];
    }

    /**
     * Sets document_complete_and_legible
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null $document_complete_and_legible document_complete_and_legible
     *
     * @return self
     */
    public function setDocumentCompleteAndLegible($document_complete_and_legible)
    {
        if (is_null($document_complete_and_legible)) {
            throw new \InvalidArgumentException('non-nullable document_complete_and_legible cannot be null');
        }
        $this->container['document_complete_and_legible'] = $document_complete_and_legible;

        return $this;
    }

    /**
     * Gets document_age_valid
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null
     */
    public function getDocumentAgeValid()
    {
        return $this->container['document_age_valid'];
    }

    /**
     * Sets document_age_valid
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null $document_age_valid document_age_valid
     *
     * @return self
     */
    public function setDocumentAgeValid($document_age_valid)
    {
        if (is_null($document_age_valid)) {
            throw new \InvalidArgumentException('non-nullable document_age_valid cannot be null');
        }
        $this->container['document_age_valid'] = $document_age_valid;

        return $this;
    }

    /**
     * Gets document_unique
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null
     */
    public function getDocumentUnique()
    {
        return $this->container['document_unique'];
    }

    /**
     * Sets document_unique
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null $document_unique document_unique
     *
     * @return self
     */
    public function setDocumentUnique($document_unique)
    {
        if (is_null($document_unique)) {
            throw new \InvalidArgumentException('non-nullable document_unique cannot be null');
        }
        $this->container['document_unique'] = $document_unique;

        return $this;
    }

    /**
     * Gets category_match
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null
     */
    public function getCategoryMatch()
    {
        return $this->container['category_match'];
    }

    /**
     * Sets category_match
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth|null $category_match category_match
     *
     * @return self
     */
    public function setCategoryMatch($category_match)
    {
        if (is_null($category_match)) {
            throw new \InvalidArgumentException('non-nullable category_match cannot be null');
        }
        $this->container['category_match'] = $category_match;

        return $this;
    }

    /**
     * Gets required_fields_extracted
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth
     */
    public function getRequiredFieldsExtracted()
    {
        return $this->container['required_fields_extracted'];
    }

    /**
     * Sets required_fields_extracted
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiReviewUserCheckValidationsRefereeConfirmedDateOfBirth $required_fields_extracted required_fields_extracted
     *
     * @return self
     */
    public function setRequiredFieldsExtracted($required_fields_extracted)
    {
        if (is_null($required_fields_extracted)) {
            throw new \InvalidArgumentException('non-nullable required_fields_extracted cannot be null');
        }
        $this->container['required_fields_extracted'] = $required_fields_extracted;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


