<?php
/**
 * ApiSupportingDocEvidenceItemExtractedDetails
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Vouchsafe\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vouchsafe API docs
 *
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vouchsafe\OpenAPI\Model;

use \ArrayAccess;
use \Vouchsafe\OpenAPI\ObjectSerializer;

/**
 * ApiSupportingDocEvidenceItemExtractedDetails Class Doc Comment
 *
 * @category Class
 * @package  Vouchsafe\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ApiSupportingDocEvidenceItemExtractedDetails implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Api_SupportingDocEvidenceItem__extracted_details';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'postcode' => 'string',
        'first_line_of_address' => 'string',
        'date_of_birth' => 'string',
        'first_name' => 'string',
        'last_name' => 'string',
        'issuer' => 'string',
        'document_date' => 'string',
        'document_category' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'postcode' => null,
        'first_line_of_address' => null,
        'date_of_birth' => null,
        'first_name' => null,
        'last_name' => null,
        'issuer' => null,
        'document_date' => null,
        'document_category' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'postcode' => false,
        'first_line_of_address' => false,
        'date_of_birth' => false,
        'first_name' => false,
        'last_name' => false,
        'issuer' => false,
        'document_date' => false,
        'document_category' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'postcode' => 'postcode',
        'first_line_of_address' => 'first_line_of_address',
        'date_of_birth' => 'date_of_birth',
        'first_name' => 'first_name',
        'last_name' => 'last_name',
        'issuer' => 'issuer',
        'document_date' => 'document_date',
        'document_category' => 'document_category'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'postcode' => 'setPostcode',
        'first_line_of_address' => 'setFirstLineOfAddress',
        'date_of_birth' => 'setDateOfBirth',
        'first_name' => 'setFirstName',
        'last_name' => 'setLastName',
        'issuer' => 'setIssuer',
        'document_date' => 'setDocumentDate',
        'document_category' => 'setDocumentCategory'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'postcode' => 'getPostcode',
        'first_line_of_address' => 'getFirstLineOfAddress',
        'date_of_birth' => 'getDateOfBirth',
        'first_name' => 'getFirstName',
        'last_name' => 'getLastName',
        'issuer' => 'getIssuer',
        'document_date' => 'getDocumentDate',
        'document_category' => 'getDocumentCategory'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const DOCUMENT_CATEGORY_PAYSLIP = 'payslip';
    public const DOCUMENT_CATEGORY_PENSION_ANNUAL_STATEMENT = 'pension_annual_statement';
    public const DOCUMENT_CATEGORY_BENEFITS_LETTER = 'benefits_letter';
    public const DOCUMENT_CATEGORY_HMPPS_LETTER = 'hmpps_letter';
    public const DOCUMENT_CATEGORY_NHS_LETTER = 'nhs_letter';
    public const DOCUMENT_CATEGORY_BANK_STATEMENT = 'bank_statement';
    public const DOCUMENT_CATEGORY_CREDIT_CARD_STATEMENT = 'credit_card_statement';
    public const DOCUMENT_CATEGORY_MORTGAGE_STATEMENT = 'mortgage_statement';
    public const DOCUMENT_CATEGORY_UTILITY_BILL = 'utility_bill';
    public const DOCUMENT_CATEGORY_MOBILE_PHONE_BILL = 'mobile_phone_bill';
    public const DOCUMENT_CATEGORY_BIRTH_OR_ADOPTION_CERTIFICATE = 'birth_or_adoption_certificate';
    public const DOCUMENT_CATEGORY_MARRIAGE_CERTIFICATE = 'marriage_certificate';
    public const DOCUMENT_CATEGORY_NATURALISATION_OR_REG_CERTIFICATE = 'naturalisation_or_reg_certificate';
    public const DOCUMENT_CATEGORY_EDUCATION_CERTIFICATE = 'education_certificate';
    public const DOCUMENT_CATEGORY_PAYE_TAX_SUMMARY = 'paye_tax_summary';
    public const DOCUMENT_CATEGORY_INSURANCE_POLICY_AGREEMENT = 'insurance_policy_agreement';
    public const DOCUMENT_CATEGORY_OLDER_PERSON_BUS_PASS = 'older_person_bus_pass';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDocumentCategoryAllowableValues()
    {
        return [
            self::DOCUMENT_CATEGORY_PAYSLIP,
            self::DOCUMENT_CATEGORY_PENSION_ANNUAL_STATEMENT,
            self::DOCUMENT_CATEGORY_BENEFITS_LETTER,
            self::DOCUMENT_CATEGORY_HMPPS_LETTER,
            self::DOCUMENT_CATEGORY_NHS_LETTER,
            self::DOCUMENT_CATEGORY_BANK_STATEMENT,
            self::DOCUMENT_CATEGORY_CREDIT_CARD_STATEMENT,
            self::DOCUMENT_CATEGORY_MORTGAGE_STATEMENT,
            self::DOCUMENT_CATEGORY_UTILITY_BILL,
            self::DOCUMENT_CATEGORY_MOBILE_PHONE_BILL,
            self::DOCUMENT_CATEGORY_BIRTH_OR_ADOPTION_CERTIFICATE,
            self::DOCUMENT_CATEGORY_MARRIAGE_CERTIFICATE,
            self::DOCUMENT_CATEGORY_NATURALISATION_OR_REG_CERTIFICATE,
            self::DOCUMENT_CATEGORY_EDUCATION_CERTIFICATE,
            self::DOCUMENT_CATEGORY_PAYE_TAX_SUMMARY,
            self::DOCUMENT_CATEGORY_INSURANCE_POLICY_AGREEMENT,
            self::DOCUMENT_CATEGORY_OLDER_PERSON_BUS_PASS,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('postcode', $data ?? [], null);
        $this->setIfExists('first_line_of_address', $data ?? [], null);
        $this->setIfExists('date_of_birth', $data ?? [], null);
        $this->setIfExists('first_name', $data ?? [], null);
        $this->setIfExists('last_name', $data ?? [], null);
        $this->setIfExists('issuer', $data ?? [], null);
        $this->setIfExists('document_date', $data ?? [], null);
        $this->setIfExists('document_category', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['first_name'] === null) {
            $invalidProperties[] = "'first_name' can't be null";
        }
        if ($this->container['last_name'] === null) {
            $invalidProperties[] = "'last_name' can't be null";
        }
        if ($this->container['issuer'] === null) {
            $invalidProperties[] = "'issuer' can't be null";
        }
        if ($this->container['document_date'] === null) {
            $invalidProperties[] = "'document_date' can't be null";
        }
        if ($this->container['document_category'] === null) {
            $invalidProperties[] = "'document_category' can't be null";
        }
        $allowedValues = $this->getDocumentCategoryAllowableValues();
        if (!is_null($this->container['document_category']) && !in_array($this->container['document_category'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'document_category', must be one of '%s'",
                $this->container['document_category'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets postcode
     *
     * @return string|null
     */
    public function getPostcode()
    {
        return $this->container['postcode'];
    }

    /**
     * Sets postcode
     *
     * @param string|null $postcode postcode
     *
     * @return self
     */
    public function setPostcode($postcode)
    {
        if (is_null($postcode)) {
            throw new \InvalidArgumentException('non-nullable postcode cannot be null');
        }
        $this->container['postcode'] = $postcode;

        return $this;
    }

    /**
     * Gets first_line_of_address
     *
     * @return string|null
     */
    public function getFirstLineOfAddress()
    {
        return $this->container['first_line_of_address'];
    }

    /**
     * Sets first_line_of_address
     *
     * @param string|null $first_line_of_address first_line_of_address
     *
     * @return self
     */
    public function setFirstLineOfAddress($first_line_of_address)
    {
        if (is_null($first_line_of_address)) {
            throw new \InvalidArgumentException('non-nullable first_line_of_address cannot be null');
        }
        $this->container['first_line_of_address'] = $first_line_of_address;

        return $this;
    }

    /**
     * Gets date_of_birth
     *
     * @return string|null
     */
    public function getDateOfBirth()
    {
        return $this->container['date_of_birth'];
    }

    /**
     * Sets date_of_birth
     *
     * @param string|null $date_of_birth date_of_birth
     *
     * @return self
     */
    public function setDateOfBirth($date_of_birth)
    {
        if (is_null($date_of_birth)) {
            throw new \InvalidArgumentException('non-nullable date_of_birth cannot be null');
        }
        $this->container['date_of_birth'] = $date_of_birth;

        return $this;
    }

    /**
     * Gets first_name
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->container['first_name'];
    }

    /**
     * Sets first_name
     *
     * @param string $first_name first_name
     *
     * @return self
     */
    public function setFirstName($first_name)
    {
        if (is_null($first_name)) {
            throw new \InvalidArgumentException('non-nullable first_name cannot be null');
        }
        $this->container['first_name'] = $first_name;

        return $this;
    }

    /**
     * Gets last_name
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->container['last_name'];
    }

    /**
     * Sets last_name
     *
     * @param string $last_name last_name
     *
     * @return self
     */
    public function setLastName($last_name)
    {
        if (is_null($last_name)) {
            throw new \InvalidArgumentException('non-nullable last_name cannot be null');
        }
        $this->container['last_name'] = $last_name;

        return $this;
    }

    /**
     * Gets issuer
     *
     * @return string
     */
    public function getIssuer()
    {
        return $this->container['issuer'];
    }

    /**
     * Sets issuer
     *
     * @param string $issuer issuer
     *
     * @return self
     */
    public function setIssuer($issuer)
    {
        if (is_null($issuer)) {
            throw new \InvalidArgumentException('non-nullable issuer cannot be null');
        }
        $this->container['issuer'] = $issuer;

        return $this;
    }

    /**
     * Gets document_date
     *
     * @return string
     */
    public function getDocumentDate()
    {
        return $this->container['document_date'];
    }

    /**
     * Sets document_date
     *
     * @param string $document_date document_date
     *
     * @return self
     */
    public function setDocumentDate($document_date)
    {
        if (is_null($document_date)) {
            throw new \InvalidArgumentException('non-nullable document_date cannot be null');
        }
        $this->container['document_date'] = $document_date;

        return $this;
    }

    /**
     * Gets document_category
     *
     * @return string
     */
    public function getDocumentCategory()
    {
        return $this->container['document_category'];
    }

    /**
     * Sets document_category
     *
     * @param string $document_category document_category
     *
     * @return self
     */
    public function setDocumentCategory($document_category)
    {
        if (is_null($document_category)) {
            throw new \InvalidArgumentException('non-nullable document_category cannot be null');
        }
        $allowedValues = $this->getDocumentCategoryAllowableValues();
        if (!in_array($document_category, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'document_category', must be one of '%s'",
                    $document_category,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['document_category'] = $document_category;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


