<?php
/**
 * ApiVerificationCheckAnyOf7Validations
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Vouchsafe\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vouchsafe API docs
 *
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vouchsafe\OpenAPI\Model;

use \ArrayAccess;
use \Vouchsafe\OpenAPI\ObjectSerializer;

/**
 * ApiVerificationCheckAnyOf7Validations Class Doc Comment
 *
 * @category Class
 * @package  Vouchsafe\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ApiVerificationCheckAnyOf7Validations implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Api_VerificationCheck__anyOf_7_validations';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'face_match' => '\Vouchsafe\OpenAPI\Model\ApiVerificationCheckAnyOfValidationsRefereeDissimilarityCheck',
        'evisa_not_expired' => '\Vouchsafe\OpenAPI\Model\ApiVerificationCheckAnyOf3ValidationsRefereeConfirmedDateOfBirth',
        'evisa_started' => '\Vouchsafe\OpenAPI\Model\ApiVerificationCheckAnyOf3ValidationsRefereeConfirmedDateOfBirth',
        'required_fields_extracted' => '\Vouchsafe\OpenAPI\Model\ApiVerificationCheckAnyOf3ValidationsRefereeConfirmedDateOfBirth',
        'evisa_exists' => '\Vouchsafe\OpenAPI\Model\ApiVerificationCheckAnyOf3ValidationsRefereeConfirmedDateOfBirth'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'face_match' => null,
        'evisa_not_expired' => null,
        'evisa_started' => null,
        'required_fields_extracted' => null,
        'evisa_exists' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'face_match' => false,
        'evisa_not_expired' => false,
        'evisa_started' => false,
        'required_fields_extracted' => false,
        'evisa_exists' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'face_match' => 'face_match',
        'evisa_not_expired' => 'evisa_not_expired',
        'evisa_started' => 'evisa_started',
        'required_fields_extracted' => 'required_fields_extracted',
        'evisa_exists' => 'evisa_exists'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'face_match' => 'setFaceMatch',
        'evisa_not_expired' => 'setEvisaNotExpired',
        'evisa_started' => 'setEvisaStarted',
        'required_fields_extracted' => 'setRequiredFieldsExtracted',
        'evisa_exists' => 'setEvisaExists'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'face_match' => 'getFaceMatch',
        'evisa_not_expired' => 'getEvisaNotExpired',
        'evisa_started' => 'getEvisaStarted',
        'required_fields_extracted' => 'getRequiredFieldsExtracted',
        'evisa_exists' => 'getEvisaExists'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('face_match', $data ?? [], null);
        $this->setIfExists('evisa_not_expired', $data ?? [], null);
        $this->setIfExists('evisa_started', $data ?? [], null);
        $this->setIfExists('required_fields_extracted', $data ?? [], null);
        $this->setIfExists('evisa_exists', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['evisa_not_expired'] === null) {
            $invalidProperties[] = "'evisa_not_expired' can't be null";
        }
        if ($this->container['evisa_started'] === null) {
            $invalidProperties[] = "'evisa_started' can't be null";
        }
        if ($this->container['required_fields_extracted'] === null) {
            $invalidProperties[] = "'required_fields_extracted' can't be null";
        }
        if ($this->container['evisa_exists'] === null) {
            $invalidProperties[] = "'evisa_exists' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets face_match
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiVerificationCheckAnyOfValidationsRefereeDissimilarityCheck|null
     */
    public function getFaceMatch()
    {
        return $this->container['face_match'];
    }

    /**
     * Sets face_match
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiVerificationCheckAnyOfValidationsRefereeDissimilarityCheck|null $face_match face_match
     *
     * @return self
     */
    public function setFaceMatch($face_match)
    {
        if (is_null($face_match)) {
            throw new \InvalidArgumentException('non-nullable face_match cannot be null');
        }
        $this->container['face_match'] = $face_match;

        return $this;
    }

    /**
     * Gets evisa_not_expired
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiVerificationCheckAnyOf3ValidationsRefereeConfirmedDateOfBirth
     */
    public function getEvisaNotExpired()
    {
        return $this->container['evisa_not_expired'];
    }

    /**
     * Sets evisa_not_expired
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiVerificationCheckAnyOf3ValidationsRefereeConfirmedDateOfBirth $evisa_not_expired evisa_not_expired
     *
     * @return self
     */
    public function setEvisaNotExpired($evisa_not_expired)
    {
        if (is_null($evisa_not_expired)) {
            throw new \InvalidArgumentException('non-nullable evisa_not_expired cannot be null');
        }
        $this->container['evisa_not_expired'] = $evisa_not_expired;

        return $this;
    }

    /**
     * Gets evisa_started
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiVerificationCheckAnyOf3ValidationsRefereeConfirmedDateOfBirth
     */
    public function getEvisaStarted()
    {
        return $this->container['evisa_started'];
    }

    /**
     * Sets evisa_started
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiVerificationCheckAnyOf3ValidationsRefereeConfirmedDateOfBirth $evisa_started evisa_started
     *
     * @return self
     */
    public function setEvisaStarted($evisa_started)
    {
        if (is_null($evisa_started)) {
            throw new \InvalidArgumentException('non-nullable evisa_started cannot be null');
        }
        $this->container['evisa_started'] = $evisa_started;

        return $this;
    }

    /**
     * Gets required_fields_extracted
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiVerificationCheckAnyOf3ValidationsRefereeConfirmedDateOfBirth
     */
    public function getRequiredFieldsExtracted()
    {
        return $this->container['required_fields_extracted'];
    }

    /**
     * Sets required_fields_extracted
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiVerificationCheckAnyOf3ValidationsRefereeConfirmedDateOfBirth $required_fields_extracted required_fields_extracted
     *
     * @return self
     */
    public function setRequiredFieldsExtracted($required_fields_extracted)
    {
        if (is_null($required_fields_extracted)) {
            throw new \InvalidArgumentException('non-nullable required_fields_extracted cannot be null');
        }
        $this->container['required_fields_extracted'] = $required_fields_extracted;

        return $this;
    }

    /**
     * Gets evisa_exists
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiVerificationCheckAnyOf3ValidationsRefereeConfirmedDateOfBirth
     */
    public function getEvisaExists()
    {
        return $this->container['evisa_exists'];
    }

    /**
     * Sets evisa_exists
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiVerificationCheckAnyOf3ValidationsRefereeConfirmedDateOfBirth $evisa_exists evisa_exists
     *
     * @return self
     */
    public function setEvisaExists($evisa_exists)
    {
        if (is_null($evisa_exists)) {
            throw new \InvalidArgumentException('non-nullable evisa_exists cannot be null');
        }
        $this->container['evisa_exists'] = $evisa_exists;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


