<?php
/**
 * ApiVerificationEnrichmentAnyOf2DetailsValidations
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Vouchsafe\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vouchsafe API docs
 *
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vouchsafe\OpenAPI\Model;

use \ArrayAccess;
use \Vouchsafe\OpenAPI\ObjectSerializer;

/**
 * ApiVerificationEnrichmentAnyOf2DetailsValidations Class Doc Comment
 *
 * @category Class
 * @package  Vouchsafe\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ApiVerificationEnrichmentAnyOf2DetailsValidations implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Api_VerificationEnrichment__anyOf_2_details_validations';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'not_disposable_email' => '\Vouchsafe\OpenAPI\Model\ApiVerificationCheckAnyOf3ValidationsRefereeConfirmedDateOfBirth',
        'no_known_fraudster_match' => '\Vouchsafe\OpenAPI\Model\ApiVerificationEnrichmentAnyOf2DetailsValidationsNoKnownFraudsterMatch',
        'normal_velocity_detected' => '\Vouchsafe\OpenAPI\Model\ApiVerificationCheckAnyOf3ValidationsRefereeConfirmedDateOfBirth'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'not_disposable_email' => null,
        'no_known_fraudster_match' => null,
        'normal_velocity_detected' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'not_disposable_email' => false,
        'no_known_fraudster_match' => false,
        'normal_velocity_detected' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'not_disposable_email' => 'not_disposable_email',
        'no_known_fraudster_match' => 'no_known_fraudster_match',
        'normal_velocity_detected' => 'normal_velocity_detected'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'not_disposable_email' => 'setNotDisposableEmail',
        'no_known_fraudster_match' => 'setNoKnownFraudsterMatch',
        'normal_velocity_detected' => 'setNormalVelocityDetected'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'not_disposable_email' => 'getNotDisposableEmail',
        'no_known_fraudster_match' => 'getNoKnownFraudsterMatch',
        'normal_velocity_detected' => 'getNormalVelocityDetected'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('not_disposable_email', $data ?? [], null);
        $this->setIfExists('no_known_fraudster_match', $data ?? [], null);
        $this->setIfExists('normal_velocity_detected', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['no_known_fraudster_match'] === null) {
            $invalidProperties[] = "'no_known_fraudster_match' can't be null";
        }
        if ($this->container['normal_velocity_detected'] === null) {
            $invalidProperties[] = "'normal_velocity_detected' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets not_disposable_email
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiVerificationCheckAnyOf3ValidationsRefereeConfirmedDateOfBirth|null
     */
    public function getNotDisposableEmail()
    {
        return $this->container['not_disposable_email'];
    }

    /**
     * Sets not_disposable_email
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiVerificationCheckAnyOf3ValidationsRefereeConfirmedDateOfBirth|null $not_disposable_email not_disposable_email
     *
     * @return self
     */
    public function setNotDisposableEmail($not_disposable_email)
    {
        if (is_null($not_disposable_email)) {
            throw new \InvalidArgumentException('non-nullable not_disposable_email cannot be null');
        }
        $this->container['not_disposable_email'] = $not_disposable_email;

        return $this;
    }

    /**
     * Gets no_known_fraudster_match
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiVerificationEnrichmentAnyOf2DetailsValidationsNoKnownFraudsterMatch
     */
    public function getNoKnownFraudsterMatch()
    {
        return $this->container['no_known_fraudster_match'];
    }

    /**
     * Sets no_known_fraudster_match
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiVerificationEnrichmentAnyOf2DetailsValidationsNoKnownFraudsterMatch $no_known_fraudster_match no_known_fraudster_match
     *
     * @return self
     */
    public function setNoKnownFraudsterMatch($no_known_fraudster_match)
    {
        if (is_null($no_known_fraudster_match)) {
            throw new \InvalidArgumentException('non-nullable no_known_fraudster_match cannot be null');
        }
        $this->container['no_known_fraudster_match'] = $no_known_fraudster_match;

        return $this;
    }

    /**
     * Gets normal_velocity_detected
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiVerificationCheckAnyOf3ValidationsRefereeConfirmedDateOfBirth
     */
    public function getNormalVelocityDetected()
    {
        return $this->container['normal_velocity_detected'];
    }

    /**
     * Sets normal_velocity_detected
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiVerificationCheckAnyOf3ValidationsRefereeConfirmedDateOfBirth $normal_velocity_detected normal_velocity_detected
     *
     * @return self
     */
    public function setNormalVelocityDetected($normal_velocity_detected)
    {
        if (is_null($normal_velocity_detected)) {
            throw new \InvalidArgumentException('non-nullable normal_velocity_detected cannot be null');
        }
        $this->container['normal_velocity_detected'] = $normal_velocity_detected;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


