<?php
/**
 * Enrichments
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Vouchsafe\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vouchsafe API docs
 *
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vouchsafe\OpenAPI\Model;

use \ArrayAccess;
use \Vouchsafe\OpenAPI\ObjectSerializer;

/**
 * Enrichments Class Doc Comment
 *
 * @category Class
 * @package  Vouchsafe\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Enrichments implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Enrichments';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'aml' => '\Vouchsafe\OpenAPI\Model\EnrichmentVerificationReport',
        'online_footprint' => '\Vouchsafe\OpenAPI\Model\EnrichmentVerificationReport',
        'credit_bureau' => '\Vouchsafe\OpenAPI\Model\EnrichmentVerificationReport',
        'address_verification' => '\Vouchsafe\OpenAPI\Model\EnrichmentVerificationReport',
        'radar' => '\Vouchsafe\OpenAPI\Model\RadarResult'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'aml' => null,
        'online_footprint' => null,
        'credit_bureau' => null,
        'address_verification' => null,
        'radar' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'aml' => true,
        'online_footprint' => true,
        'credit_bureau' => true,
        'address_verification' => true,
        'radar' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'aml' => 'aml',
        'online_footprint' => 'online_footprint',
        'credit_bureau' => 'credit_bureau',
        'address_verification' => 'address_verification',
        'radar' => 'radar'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'aml' => 'setAml',
        'online_footprint' => 'setOnlineFootprint',
        'credit_bureau' => 'setCreditBureau',
        'address_verification' => 'setAddressVerification',
        'radar' => 'setRadar'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'aml' => 'getAml',
        'online_footprint' => 'getOnlineFootprint',
        'credit_bureau' => 'getCreditBureau',
        'address_verification' => 'getAddressVerification',
        'radar' => 'getRadar'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('aml', $data ?? [], null);
        $this->setIfExists('online_footprint', $data ?? [], null);
        $this->setIfExists('credit_bureau', $data ?? [], null);
        $this->setIfExists('address_verification', $data ?? [], null);
        $this->setIfExists('radar', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['aml'] === null && !$this->isNullableSetToNull('aml')) {
            $invalidProperties[] = "'aml' can't be null";
        }
        if ($this->container['online_footprint'] === null && !$this->isNullableSetToNull('online_footprint')) {
            $invalidProperties[] = "'online_footprint' can't be null";
        }
        if ($this->container['credit_bureau'] === null && !$this->isNullableSetToNull('credit_bureau')) {
            $invalidProperties[] = "'credit_bureau' can't be null";
        }
        if ($this->container['address_verification'] === null && !$this->isNullableSetToNull('address_verification')) {
            $invalidProperties[] = "'address_verification' can't be null";
        }
        if ($this->container['radar'] === null && !$this->isNullableSetToNull('radar')) {
            $invalidProperties[] = "'radar' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets aml
     *
     * @return \Vouchsafe\OpenAPI\Model\EnrichmentVerificationReport|null
     */
    public function getAml()
    {
        return $this->container['aml'];
    }

    /**
     * Sets aml
     *
     * @param \Vouchsafe\OpenAPI\Model\EnrichmentVerificationReport|null $aml aml
     *
     * @return self
     */
    public function setAml($aml)
    {
        if (is_null($aml)) {
            array_push($this->openAPINullablesSetToNull, 'aml');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('aml', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['aml'] = $aml;

        return $this;
    }

    /**
     * Gets online_footprint
     *
     * @return \Vouchsafe\OpenAPI\Model\EnrichmentVerificationReport|null
     */
    public function getOnlineFootprint()
    {
        return $this->container['online_footprint'];
    }

    /**
     * Sets online_footprint
     *
     * @param \Vouchsafe\OpenAPI\Model\EnrichmentVerificationReport|null $online_footprint online_footprint
     *
     * @return self
     */
    public function setOnlineFootprint($online_footprint)
    {
        if (is_null($online_footprint)) {
            array_push($this->openAPINullablesSetToNull, 'online_footprint');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('online_footprint', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['online_footprint'] = $online_footprint;

        return $this;
    }

    /**
     * Gets credit_bureau
     *
     * @return \Vouchsafe\OpenAPI\Model\EnrichmentVerificationReport|null
     */
    public function getCreditBureau()
    {
        return $this->container['credit_bureau'];
    }

    /**
     * Sets credit_bureau
     *
     * @param \Vouchsafe\OpenAPI\Model\EnrichmentVerificationReport|null $credit_bureau credit_bureau
     *
     * @return self
     */
    public function setCreditBureau($credit_bureau)
    {
        if (is_null($credit_bureau)) {
            array_push($this->openAPINullablesSetToNull, 'credit_bureau');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('credit_bureau', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['credit_bureau'] = $credit_bureau;

        return $this;
    }

    /**
     * Gets address_verification
     *
     * @return \Vouchsafe\OpenAPI\Model\EnrichmentVerificationReport|null
     */
    public function getAddressVerification()
    {
        return $this->container['address_verification'];
    }

    /**
     * Sets address_verification
     *
     * @param \Vouchsafe\OpenAPI\Model\EnrichmentVerificationReport|null $address_verification address_verification
     *
     * @return self
     */
    public function setAddressVerification($address_verification)
    {
        if (is_null($address_verification)) {
            array_push($this->openAPINullablesSetToNull, 'address_verification');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('address_verification', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['address_verification'] = $address_verification;

        return $this;
    }

    /**
     * Gets radar
     *
     * @return \Vouchsafe\OpenAPI\Model\RadarResult|null
     */
    public function getRadar()
    {
        return $this->container['radar'];
    }

    /**
     * Sets radar
     *
     * @param \Vouchsafe\OpenAPI\Model\RadarResult|null $radar radar
     *
     * @return self
     */
    public function setRadar($radar)
    {
        if (is_null($radar)) {
            array_push($this->openAPINullablesSetToNull, 'radar');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('radar', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['radar'] = $radar;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


