<?php
/**
 * EvisaExistsFailedReason
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Vouchsafe\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vouchsafe API docs
 *
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vouchsafe\OpenAPI\Model;
use \Vouchsafe\OpenAPI\ObjectSerializer;

/**
 * EvisaExistsFailedReason Class Doc Comment
 *
 * @category Class
 * @package  Vouchsafe\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EvisaExistsFailedReason
{
    /**
     * Possible values of this enum
     */
    public const SHARE_CODE_ERROR = 'SHARE_CODE_ERROR';

    public const INCORRECT_DETAILS = 'INCORRECT_DETAILS';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SHARE_CODE_ERROR,
            self::INCORRECT_DETAILS
        ];
    }
}


