<?php
/**
 * GetSmartLookupResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Vouchsafe\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vouchsafe API docs
 *
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vouchsafe\OpenAPI\Model;

use \ArrayAccess;
use \Vouchsafe\OpenAPI\ObjectSerializer;

/**
 * GetSmartLookupResponse Class Doc Comment
 *
 * @category Class
 * @package  Vouchsafe\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetSmartLookupResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetSmartLookupResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'team_id' => 'string',
        'checks' => 'string[]',
        'first_name' => 'string',
        'last_name' => 'string',
        'first_line_of_address' => 'string',
        'postcode' => 'string',
        'date_of_birth' => 'string',
        'email' => 'string',
        'phone' => 'string',
        'address_verification_report' => '\Vouchsafe\OpenAPI\Model\AddressVerificationReport',
        'credit_bureau_verification_report' => '\Vouchsafe\OpenAPI\Model\CreditBureauVerificationReport',
        'online_footprint_verification_report' => '\Vouchsafe\OpenAPI\Model\OnlineFootprintVerificationReport',
        'aml_verification_report' => '\Vouchsafe\OpenAPI\Model\AmlVerificationReport',
        'metadata' => 'mixed',
        'created_at' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'team_id' => null,
        'checks' => null,
        'first_name' => null,
        'last_name' => null,
        'first_line_of_address' => null,
        'postcode' => null,
        'date_of_birth' => null,
        'email' => null,
        'phone' => null,
        'address_verification_report' => null,
        'credit_bureau_verification_report' => null,
        'online_footprint_verification_report' => null,
        'aml_verification_report' => null,
        'metadata' => null,
        'created_at' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'team_id' => false,
        'checks' => false,
        'first_name' => true,
        'last_name' => true,
        'first_line_of_address' => true,
        'postcode' => true,
        'date_of_birth' => false,
        'email' => false,
        'phone' => false,
        'address_verification_report' => false,
        'credit_bureau_verification_report' => false,
        'online_footprint_verification_report' => false,
        'aml_verification_report' => false,
        'metadata' => true,
        'created_at' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'team_id' => 'team_id',
        'checks' => 'checks',
        'first_name' => 'first_name',
        'last_name' => 'last_name',
        'first_line_of_address' => 'first_line_of_address',
        'postcode' => 'postcode',
        'date_of_birth' => 'date_of_birth',
        'email' => 'email',
        'phone' => 'phone',
        'address_verification_report' => 'address_verification_report',
        'credit_bureau_verification_report' => 'credit_bureau_verification_report',
        'online_footprint_verification_report' => 'online_footprint_verification_report',
        'aml_verification_report' => 'aml_verification_report',
        'metadata' => 'metadata',
        'created_at' => 'created_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'team_id' => 'setTeamId',
        'checks' => 'setChecks',
        'first_name' => 'setFirstName',
        'last_name' => 'setLastName',
        'first_line_of_address' => 'setFirstLineOfAddress',
        'postcode' => 'setPostcode',
        'date_of_birth' => 'setDateOfBirth',
        'email' => 'setEmail',
        'phone' => 'setPhone',
        'address_verification_report' => 'setAddressVerificationReport',
        'credit_bureau_verification_report' => 'setCreditBureauVerificationReport',
        'online_footprint_verification_report' => 'setOnlineFootprintVerificationReport',
        'aml_verification_report' => 'setAmlVerificationReport',
        'metadata' => 'setMetadata',
        'created_at' => 'setCreatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'team_id' => 'getTeamId',
        'checks' => 'getChecks',
        'first_name' => 'getFirstName',
        'last_name' => 'getLastName',
        'first_line_of_address' => 'getFirstLineOfAddress',
        'postcode' => 'getPostcode',
        'date_of_birth' => 'getDateOfBirth',
        'email' => 'getEmail',
        'phone' => 'getPhone',
        'address_verification_report' => 'getAddressVerificationReport',
        'credit_bureau_verification_report' => 'getCreditBureauVerificationReport',
        'online_footprint_verification_report' => 'getOnlineFootprintVerificationReport',
        'aml_verification_report' => 'getAmlVerificationReport',
        'metadata' => 'getMetadata',
        'created_at' => 'getCreatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const CHECKS_ADDRESS = 'Address';
    public const CHECKS_CREDIT_BUREAU = 'CreditBureau';
    public const CHECKS_ONLINE_FOOTPRINT = 'OnlineFootprint';
    public const CHECKS_AML = 'AML';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChecksAllowableValues()
    {
        return [
            self::CHECKS_ADDRESS,
            self::CHECKS_CREDIT_BUREAU,
            self::CHECKS_ONLINE_FOOTPRINT,
            self::CHECKS_AML,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('team_id', $data ?? [], null);
        $this->setIfExists('checks', $data ?? [], null);
        $this->setIfExists('first_name', $data ?? [], null);
        $this->setIfExists('last_name', $data ?? [], null);
        $this->setIfExists('first_line_of_address', $data ?? [], null);
        $this->setIfExists('postcode', $data ?? [], null);
        $this->setIfExists('date_of_birth', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('phone', $data ?? [], null);
        $this->setIfExists('address_verification_report', $data ?? [], null);
        $this->setIfExists('credit_bureau_verification_report', $data ?? [], null);
        $this->setIfExists('online_footprint_verification_report', $data ?? [], null);
        $this->setIfExists('aml_verification_report', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['team_id'] === null) {
            $invalidProperties[] = "'team_id' can't be null";
        }
        if ($this->container['checks'] === null) {
            $invalidProperties[] = "'checks' can't be null";
        }
        if ($this->container['first_name'] === null && !$this->isNullableSetToNull('first_name')) {
            $invalidProperties[] = "'first_name' can't be null";
        }
        if ($this->container['last_name'] === null && !$this->isNullableSetToNull('last_name')) {
            $invalidProperties[] = "'last_name' can't be null";
        }
        if ($this->container['first_line_of_address'] === null && !$this->isNullableSetToNull('first_line_of_address')) {
            $invalidProperties[] = "'first_line_of_address' can't be null";
        }
        if ($this->container['postcode'] === null && !$this->isNullableSetToNull('postcode')) {
            $invalidProperties[] = "'postcode' can't be null";
        }
        if ($this->container['metadata'] === null && !$this->isNullableSetToNull('metadata')) {
            $invalidProperties[] = "'metadata' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets team_id
     *
     * @return string
     */
    public function getTeamId()
    {
        return $this->container['team_id'];
    }

    /**
     * Sets team_id
     *
     * @param string $team_id team_id
     *
     * @return self
     */
    public function setTeamId($team_id)
    {
        if (is_null($team_id)) {
            throw new \InvalidArgumentException('non-nullable team_id cannot be null');
        }
        $this->container['team_id'] = $team_id;

        return $this;
    }

    /**
     * Gets checks
     *
     * @return string[]
     */
    public function getChecks()
    {
        return $this->container['checks'];
    }

    /**
     * Sets checks
     *
     * @param string[] $checks checks
     *
     * @return self
     */
    public function setChecks($checks)
    {
        if (is_null($checks)) {
            throw new \InvalidArgumentException('non-nullable checks cannot be null');
        }
        $allowedValues = $this->getChecksAllowableValues();
        if (array_diff($checks, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'checks', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['checks'] = $checks;

        return $this;
    }

    /**
     * Gets first_name
     *
     * @return string|null
     */
    public function getFirstName()
    {
        return $this->container['first_name'];
    }

    /**
     * Sets first_name
     *
     * @param string|null $first_name first_name
     *
     * @return self
     */
    public function setFirstName($first_name)
    {
        if (is_null($first_name)) {
            array_push($this->openAPINullablesSetToNull, 'first_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('first_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['first_name'] = $first_name;

        return $this;
    }

    /**
     * Gets last_name
     *
     * @return string|null
     */
    public function getLastName()
    {
        return $this->container['last_name'];
    }

    /**
     * Sets last_name
     *
     * @param string|null $last_name last_name
     *
     * @return self
     */
    public function setLastName($last_name)
    {
        if (is_null($last_name)) {
            array_push($this->openAPINullablesSetToNull, 'last_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_name'] = $last_name;

        return $this;
    }

    /**
     * Gets first_line_of_address
     *
     * @return string|null
     */
    public function getFirstLineOfAddress()
    {
        return $this->container['first_line_of_address'];
    }

    /**
     * Sets first_line_of_address
     *
     * @param string|null $first_line_of_address first_line_of_address
     *
     * @return self
     */
    public function setFirstLineOfAddress($first_line_of_address)
    {
        if (is_null($first_line_of_address)) {
            array_push($this->openAPINullablesSetToNull, 'first_line_of_address');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('first_line_of_address', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['first_line_of_address'] = $first_line_of_address;

        return $this;
    }

    /**
     * Gets postcode
     *
     * @return string|null
     */
    public function getPostcode()
    {
        return $this->container['postcode'];
    }

    /**
     * Sets postcode
     *
     * @param string|null $postcode postcode
     *
     * @return self
     */
    public function setPostcode($postcode)
    {
        if (is_null($postcode)) {
            array_push($this->openAPINullablesSetToNull, 'postcode');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('postcode', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['postcode'] = $postcode;

        return $this;
    }

    /**
     * Gets date_of_birth
     *
     * @return string|null
     */
    public function getDateOfBirth()
    {
        return $this->container['date_of_birth'];
    }

    /**
     * Sets date_of_birth
     *
     * @param string|null $date_of_birth date_of_birth
     *
     * @return self
     */
    public function setDateOfBirth($date_of_birth)
    {
        if (is_null($date_of_birth)) {
            throw new \InvalidArgumentException('non-nullable date_of_birth cannot be null');
        }
        $this->container['date_of_birth'] = $date_of_birth;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email email
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string|null
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string|null $phone phone
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            throw new \InvalidArgumentException('non-nullable phone cannot be null');
        }
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets address_verification_report
     *
     * @return \Vouchsafe\OpenAPI\Model\AddressVerificationReport|null
     */
    public function getAddressVerificationReport()
    {
        return $this->container['address_verification_report'];
    }

    /**
     * Sets address_verification_report
     *
     * @param \Vouchsafe\OpenAPI\Model\AddressVerificationReport|null $address_verification_report address_verification_report
     *
     * @return self
     */
    public function setAddressVerificationReport($address_verification_report)
    {
        if (is_null($address_verification_report)) {
            throw new \InvalidArgumentException('non-nullable address_verification_report cannot be null');
        }
        $this->container['address_verification_report'] = $address_verification_report;

        return $this;
    }

    /**
     * Gets credit_bureau_verification_report
     *
     * @return \Vouchsafe\OpenAPI\Model\CreditBureauVerificationReport|null
     */
    public function getCreditBureauVerificationReport()
    {
        return $this->container['credit_bureau_verification_report'];
    }

    /**
     * Sets credit_bureau_verification_report
     *
     * @param \Vouchsafe\OpenAPI\Model\CreditBureauVerificationReport|null $credit_bureau_verification_report credit_bureau_verification_report
     *
     * @return self
     */
    public function setCreditBureauVerificationReport($credit_bureau_verification_report)
    {
        if (is_null($credit_bureau_verification_report)) {
            throw new \InvalidArgumentException('non-nullable credit_bureau_verification_report cannot be null');
        }
        $this->container['credit_bureau_verification_report'] = $credit_bureau_verification_report;

        return $this;
    }

    /**
     * Gets online_footprint_verification_report
     *
     * @return \Vouchsafe\OpenAPI\Model\OnlineFootprintVerificationReport|null
     */
    public function getOnlineFootprintVerificationReport()
    {
        return $this->container['online_footprint_verification_report'];
    }

    /**
     * Sets online_footprint_verification_report
     *
     * @param \Vouchsafe\OpenAPI\Model\OnlineFootprintVerificationReport|null $online_footprint_verification_report online_footprint_verification_report
     *
     * @return self
     */
    public function setOnlineFootprintVerificationReport($online_footprint_verification_report)
    {
        if (is_null($online_footprint_verification_report)) {
            throw new \InvalidArgumentException('non-nullable online_footprint_verification_report cannot be null');
        }
        $this->container['online_footprint_verification_report'] = $online_footprint_verification_report;

        return $this;
    }

    /**
     * Gets aml_verification_report
     *
     * @return \Vouchsafe\OpenAPI\Model\AmlVerificationReport|null
     */
    public function getAmlVerificationReport()
    {
        return $this->container['aml_verification_report'];
    }

    /**
     * Sets aml_verification_report
     *
     * @param \Vouchsafe\OpenAPI\Model\AmlVerificationReport|null $aml_verification_report aml_verification_report
     *
     * @return self
     */
    public function setAmlVerificationReport($aml_verification_report)
    {
        if (is_null($aml_verification_report)) {
            throw new \InvalidArgumentException('non-nullable aml_verification_report cannot be null');
        }
        $this->container['aml_verification_report'] = $aml_verification_report;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return mixed|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param mixed|null $metadata Extra information to aid debugging. May change without notice.
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            array_push($this->openAPINullablesSetToNull, 'metadata');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('metadata', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


