<?php
/**
 * ImmigrationStatusVerificationResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Vouchsafe\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vouchsafe API docs
 *
 * Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@vouchsafe.id
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vouchsafe\OpenAPI\Model;

use \ArrayAccess;
use \Vouchsafe\OpenAPI\ObjectSerializer;

/**
 * ImmigrationStatusVerificationResponse Class Doc Comment
 *
 * @category Class
 * @package  Vouchsafe\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ImmigrationStatusVerificationResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ImmigrationStatusVerificationResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'verification_method' => 'string',
        'evidence_type' => 'string',
        'outcome' => '\Vouchsafe\OpenAPI\Model\ApiValidationStatus',
        'billable' => 'bool',
        'extracted_details' => '\Vouchsafe\OpenAPI\Model\ImmigrationStatusVerificationResponseExtractedDetails',
        'artefacts' => '\Vouchsafe\OpenAPI\Model\EvisaArtefact[]',
        'validations' => '\Vouchsafe\OpenAPI\Model\ImmigrationStatusVerificationResponseValidations'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'verification_method' => null,
        'evidence_type' => null,
        'outcome' => null,
        'billable' => null,
        'extracted_details' => null,
        'artefacts' => null,
        'validations' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'verification_method' => false,
        'evidence_type' => false,
        'outcome' => false,
        'billable' => false,
        'extracted_details' => false,
        'artefacts' => false,
        'validations' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'verification_method' => 'verification_method',
        'evidence_type' => 'evidence_type',
        'outcome' => 'outcome',
        'billable' => 'billable',
        'extracted_details' => 'extracted_details',
        'artefacts' => 'artefacts',
        'validations' => 'validations'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'verification_method' => 'setVerificationMethod',
        'evidence_type' => 'setEvidenceType',
        'outcome' => 'setOutcome',
        'billable' => 'setBillable',
        'extracted_details' => 'setExtractedDetails',
        'artefacts' => 'setArtefacts',
        'validations' => 'setValidations'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'verification_method' => 'getVerificationMethod',
        'evidence_type' => 'getEvidenceType',
        'outcome' => 'getOutcome',
        'billable' => 'getBillable',
        'extracted_details' => 'getExtractedDetails',
        'artefacts' => 'getArtefacts',
        'validations' => 'getValidations'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const VERIFICATION_METHOD_EVISA = 'evisa';
    public const EVIDENCE_TYPE_IMMIGRATION_STATUS = 'immigration_status';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getVerificationMethodAllowableValues()
    {
        return [
            self::VERIFICATION_METHOD_EVISA,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEvidenceTypeAllowableValues()
    {
        return [
            self::EVIDENCE_TYPE_IMMIGRATION_STATUS,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('verification_method', $data ?? [], null);
        $this->setIfExists('evidence_type', $data ?? [], null);
        $this->setIfExists('outcome', $data ?? [], null);
        $this->setIfExists('billable', $data ?? [], null);
        $this->setIfExists('extracted_details', $data ?? [], null);
        $this->setIfExists('artefacts', $data ?? [], null);
        $this->setIfExists('validations', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['verification_method'] === null) {
            $invalidProperties[] = "'verification_method' can't be null";
        }
        $allowedValues = $this->getVerificationMethodAllowableValues();
        if (!is_null($this->container['verification_method']) && !in_array($this->container['verification_method'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'verification_method', must be one of '%s'",
                $this->container['verification_method'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['evidence_type'] === null) {
            $invalidProperties[] = "'evidence_type' can't be null";
        }
        $allowedValues = $this->getEvidenceTypeAllowableValues();
        if (!is_null($this->container['evidence_type']) && !in_array($this->container['evidence_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'evidence_type', must be one of '%s'",
                $this->container['evidence_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['outcome'] === null) {
            $invalidProperties[] = "'outcome' can't be null";
        }
        if ($this->container['billable'] === null) {
            $invalidProperties[] = "'billable' can't be null";
        }
        if ($this->container['extracted_details'] === null) {
            $invalidProperties[] = "'extracted_details' can't be null";
        }
        if ($this->container['artefacts'] === null) {
            $invalidProperties[] = "'artefacts' can't be null";
        }
        if ($this->container['validations'] === null) {
            $invalidProperties[] = "'validations' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets verification_method
     *
     * @return string
     */
    public function getVerificationMethod()
    {
        return $this->container['verification_method'];
    }

    /**
     * Sets verification_method
     *
     * @param string $verification_method verification_method
     *
     * @return self
     */
    public function setVerificationMethod($verification_method)
    {
        if (is_null($verification_method)) {
            throw new \InvalidArgumentException('non-nullable verification_method cannot be null');
        }
        $allowedValues = $this->getVerificationMethodAllowableValues();
        if (!in_array($verification_method, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'verification_method', must be one of '%s'",
                    $verification_method,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['verification_method'] = $verification_method;

        return $this;
    }

    /**
     * Gets evidence_type
     *
     * @return string
     */
    public function getEvidenceType()
    {
        return $this->container['evidence_type'];
    }

    /**
     * Sets evidence_type
     *
     * @param string $evidence_type evidence_type
     *
     * @return self
     */
    public function setEvidenceType($evidence_type)
    {
        if (is_null($evidence_type)) {
            throw new \InvalidArgumentException('non-nullable evidence_type cannot be null');
        }
        $allowedValues = $this->getEvidenceTypeAllowableValues();
        if (!in_array($evidence_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'evidence_type', must be one of '%s'",
                    $evidence_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['evidence_type'] = $evidence_type;

        return $this;
    }

    /**
     * Gets outcome
     *
     * @return \Vouchsafe\OpenAPI\Model\ApiValidationStatus
     */
    public function getOutcome()
    {
        return $this->container['outcome'];
    }

    /**
     * Sets outcome
     *
     * @param \Vouchsafe\OpenAPI\Model\ApiValidationStatus $outcome outcome
     *
     * @return self
     */
    public function setOutcome($outcome)
    {
        if (is_null($outcome)) {
            throw new \InvalidArgumentException('non-nullable outcome cannot be null');
        }
        $this->container['outcome'] = $outcome;

        return $this;
    }

    /**
     * Gets billable
     *
     * @return bool
     */
    public function getBillable()
    {
        return $this->container['billable'];
    }

    /**
     * Sets billable
     *
     * @param bool $billable Whether this API call is billable. `true` when the eVisa was found on GOV.UK, `false` when the share code or date of birth was invalid.
     *
     * @return self
     */
    public function setBillable($billable)
    {
        if (is_null($billable)) {
            throw new \InvalidArgumentException('non-nullable billable cannot be null');
        }
        $this->container['billable'] = $billable;

        return $this;
    }

    /**
     * Gets extracted_details
     *
     * @return \Vouchsafe\OpenAPI\Model\ImmigrationStatusVerificationResponseExtractedDetails
     */
    public function getExtractedDetails()
    {
        return $this->container['extracted_details'];
    }

    /**
     * Sets extracted_details
     *
     * @param \Vouchsafe\OpenAPI\Model\ImmigrationStatusVerificationResponseExtractedDetails $extracted_details extracted_details
     *
     * @return self
     */
    public function setExtractedDetails($extracted_details)
    {
        if (is_null($extracted_details)) {
            throw new \InvalidArgumentException('non-nullable extracted_details cannot be null');
        }
        $this->container['extracted_details'] = $extracted_details;

        return $this;
    }

    /**
     * Gets artefacts
     *
     * @return \Vouchsafe\OpenAPI\Model\EvisaArtefact[]
     */
    public function getArtefacts()
    {
        return $this->container['artefacts'];
    }

    /**
     * Sets artefacts
     *
     * @param \Vouchsafe\OpenAPI\Model\EvisaArtefact[] $artefacts artefacts
     *
     * @return self
     */
    public function setArtefacts($artefacts)
    {
        if (is_null($artefacts)) {
            throw new \InvalidArgumentException('non-nullable artefacts cannot be null');
        }
        $this->container['artefacts'] = $artefacts;

        return $this;
    }

    /**
     * Gets validations
     *
     * @return \Vouchsafe\OpenAPI\Model\ImmigrationStatusVerificationResponseValidations
     */
    public function getValidations()
    {
        return $this->container['validations'];
    }

    /**
     * Sets validations
     *
     * @param \Vouchsafe\OpenAPI\Model\ImmigrationStatusVerificationResponseValidations $validations validations
     *
     * @return self
     */
    public function setValidations($validations)
    {
        if (is_null($validations)) {
            throw new \InvalidArgumentException('non-nullable validations cannot be null');
        }
        $this->container['validations'] = $validations;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


